apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-09216bab7a191b4de
  cidr: "192.168.0.0/16"
  subnets:
    public:
      MyStack-PublicSubnet01:
        id: subnet-0a4d839e87a357ae9
      MyStack-PublicSubnet02:
        id: subnet-0202a48d8354c1776
    private:
      MyStack-PrivateSubnet01:
        id: subnet-0bdba521bebfdf333
      MyStack-PrivateSubnet02:
        id: subnet-0d4a7e07bb8415ee3

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 1
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
