apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-04f2fcc965fde067e
  cidr: "192.168.0.0/16"
  subnets:
    public:
      MyStack-PublicSubnet01:
        id: subnet-05d9185b5ad22d917
      MyStack-PublicSubnet02:
        id: subnet-042320fb8a178d311
    private:
      MyStack-PrivateSubnet01:
        id: subnet-0e708ea995253880f
      MyStack-PrivateSubnet02:
        id: subnet-02a068125add6eb41

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 1
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
