apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-096019d5034ed9124
  cidr: "192.168.0.0/16"
  subnets:
    public:
      MyStack-PublicSubnet01:
        id: subnet-0da981a03c4aadcbf
      MyStack-PublicSubnet02:
        id: subnet-09f1dc7a05afdd7ae
    private:
      MyStack-PrivateSubnet01:
        id: subnet-01339492852a1f740
      MyStack-PrivateSubnet02:
        id: subnet-021fa5941a6f1fd81

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 1
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
