apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-0f65f8b4e3851b070
  cidr: "192.168.0.0/16"
  subnets:
    public:
      MyStack-sa1-VPC-PublicSubnet01:
        id: subnet-0fce716c1909a2d3d
      MyStack-sa1-VPC-PublicSubnet02:
        id: subnet-0722c430af27274c9
    private:
      MyStack-sa1-VPC-PrivateSubnet01:
        id: subnet-0d3a3ba47ba257dfe
      MyStack-sa1-VPC-PrivateSubnet02:
        id: subnet-04de010dbff002fd1

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 1
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
